#ifndef INTERRUPT_H
#define INTERRUPT_H

#define INTERRUPT_BASE 0x3f00b000
#define INTERRUPT_IRQ_BASIC_PENDING INTERRUPT_BASE + 0x200
#define INTERRUPT_IRQ1_PENDING INTERRUPT_BASE + 0x204
#define INTERRUPT_IRQ2_PENDING INTERRUPT_BASE + 0x208
#define INTERRUPT_FIQ_CONTROL INTERRUPT_BASE + 0x20C
#define INTERRUPT_ENABLE_IRQ1 INTERRUPT_BASE + 0x210
#define INTERRUPT_ENABLE_IRQ2 INTERRUPT_BASE + 0x214
#define INTERRUPT_ENABLE_IRQ_BASIC INTERRUPT_BASE + 0x218
#define INTERRUPT_DISABLE_IRQ1 INTERRUPT_BASE + 0x21C
#define INTERRUPT_DISABLE_IRQ2 INTERRUPT_BASE + 0x220
#define INTERRUPT_DISABLE_IRQ_BASIC INTERRUPT_BASE + 0x224
void init_interrupts();

#endif
